version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./FrontEnd:/app/FrontEnd
    working_dir: /app/FrontEnd/my-app

  backend:
    build:
      context: ./BackEnd/Amazon-clone
      dockerfile: Dockerfile.backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./BackEnd/Amazon-clone:/app
